server:
  port: 8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@10.0.3.13:8761/eureka/
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: eshop-one-service #此实例注册到eureka服务端的name
  zipkin:
    base-url: http://10.0.3.13:9411  #指定Zipkin server地址
