server:
  port: 8768
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8761/eureka/
spring:
  application:
    name: eshop-datalink-service #此实例注册到eureka服务端的name
  zipkin:
    base-url: http://localhost:9411  #指定Zipkin server地址
