server:
  port: 8766
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@10.0.3.13:8761/eureka/
spring:
  application:
    name: eshop-dataaggr-service #此实例注册到eureka服务端的name
  zipkin:
    base-url: http://10.0.3.13:9411  #指定Zipkin server地址
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://10.0.3.11:3306/eshop?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  rabbitmq:
    host: 10.0.3.11
    port: 5672
    username: rabbitadmin
    password: 123456
