server:
  port: 8764
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: greeting-service #此实例注册到eureka服务端的name
